name: Notify PR Owner

on:
  pull_request_review:
    types: ['submitted']
  pull_request:
     types:
       - opened
       - synchronize

jobs:
  assign-senior-if-mergeable:
    runs-on: ubuntu-latest
    steps:
      - name: Assign senior
        if: github.event.pull_request.mergeable
        run: <some code that assigns the senior>
