name: Notify PR Owner

on:
  pull_request:
    types:
      - labeled

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check if label is "Ready to Merge"
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            PR_LABELS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "${{ github.api_url }}/repos/${{ github.repository }}/issues/${{ github.event.number }}/labels")
            if echo "$PR_LABELS" | jq -e '.[].name' | grep -q 'Ready to Merge'; then
              echo "PR is ready to merge. Notifying the owner."
            else
              echo "PR is not labeled as 'Ready to Merge'. No action needed."
              exit 78 # Exit code 78 means a neutral action, i.e., no further action needed
            fi
          else
            echo "Event is not a pull request. No action needed."
            exit 78
          fi

      - name: Notify PR Owner
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.payload.pull_request.user.login;
            const prNumber = context.payload.pull_request.number;
            const commentBody = 'Your PR is ready to merge.';

            const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
            await octokit.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: prNumber,
              body: commentBody,
            });

